### ISSUE TITLE
Hook Snipcart account with Craft account

### ISSUE THREAD

**Issue by zizther** [FosterCommerce/snipcart-craft-plugin#28]
I know Snipcart is designed to work as a standalone solution, but I was wondering if there was a current way or any plans to allow account creation to also create a user in Craft, so that there was not a need to have 2 separate sign-ins, one for Snipcart and another for the site functionality?

Could this work already with a SSO?

**Comment by sjcallender** [comment]
Hi @zizther, great question. It comes down to authentication. As far as we can see from the Snipcart API documentation there’s currently no way to communicate to Snipcart from Craft that a customer should be considered logged in.

If that ability ever becomes possible, we'll definitely take a good look at it.
