### ISSUE TITLE
Inventory not reducing after succesfull order

### ISSUE THREAD

**Issue by noregt** [FosterCommerce/snipcart-craft-plugin#34]
Hi,
If I use the productdetails field, and order a product, I can see the order in the Craft CP and Snipcart so the webhooks are working I suppose, but the inventory is not reduced. 

"Reduce Item Quantities on Order" is set to true in the CP (tested with config file as well).

Ideally I would like to use a custom inventory field btw, but I did not see any "data-inventory-item" or similar that I can use with the buy button?

**Comment by noregt** [comment]
Hi, any progress on this issue?

**Comment by benface** [comment]
Hi @noregt, I will be looking at this tomorrow, and should have a fix sometime next week at the latest. Sorry for the delay.

**Comment by benface** [comment]
@noregt I'm not able to reproduce this locally. Is there any chance you could get in touch with us at support@fostercommerce.com? We could do a call or perhaps you could give me limited access to your project so I can investigate if you don’t mind. Sorry for the delay in getting back to you!

**Comment by noregt** [comment]
@benface I gave up on on Snipcart for the moment, if it works with the standard setup on your side let's consider it a local issue here.

**Comment by benface** [comment]
I’m really sorry if the delay in my response made you give up on Snipcart or this plugin, @noregt. If you decide to get back to it, support will be faster next time.

**Comment by noregt** [comment]
Well it was a combination of things. Snipcart itself was also very unresponsive. There was no way to reduce stock manually with the snipcart-add-item button either and never got an answer about that.

**Comment by benface** [comment]
@noregt What do you mean by “reduce stock manually with the snipcart-add-item button”? The stock is reduced automatically when an order is completed, not when `snipcart-add-item` is clicked. It can also be set manually from the Snipcart merchant dashboard. If you explain what you’re trying to achieve, perhaps I can help you?

**Comment by noregt** [comment]
I'm sorry if I'm not clear (It's some time ago by now). The point was that I wanted to parse the stock amount from craft to snipcart. If I have a new product, you can add an item with the snipcart-add-item button, but it's not possible to set the stock.  I had to do that in the snipcart interface every time. I also could not find a way to show the current stock on the website as mentioned in the snipcart Dashboard. This should be possible with your plugin, but I got stuck there too, hence why I gave up.
