### ISSUE TITLE
Return an error rather than rates response in ShippingRateEvent

### ISSUE THREAD

**Issue by tobystokes** [FosterCommerce/snipcart-craft-plugin#36]
In `ShippingRateEvent` events, is it possible to return an error instead of rates, as per
https://docs.snipcart.com/v2/webhooks/shipping#error ?
(fwiw, it's not as far as I can see. I'd like to do some validation on postcodes, and return an error if no rates because of this)

**Comment by benface** [comment]
Good idea! We’ll add that to the next release, hopefully before the end of the month.

**Comment by benface** [comment]
Added in [v1.5.5](https://github.com/FosterCommerce/snipcart-craft-plugin/releases/tag/1.5.5). Thank you for requesting this!
