### ISSUE TITLE
Deprecation Error: Elements’ `getSourceId()` method has been deprecated. Use `getCanonicalId()` instead.

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [FosterCommerce/snipcart-craft-plugin#39]
This bug appears to take place on entries with the snipcart field _and_ `devMode` set to `True`.

**To Reproduce**

1. Enable `devMode`
2. Save Entry
3. See error

**Expected behavior**

No deprecation error should appear

**Screenshots**

![Screen Shot 2021-10-26 at 12 09 51 PM](https://user-images.githubusercontent.com/39201467/138936989-86e33856-b4d0-4bce-a446-17b9279b4afd.png)

**Software**

 - Craft version: 3.7.17.2
 - Snipcart plugin version: 1.5.5
 - PHP version: 8.0.9
 - Browser Chrome

**Comment by johnnynotsolucky** [comment]
@DynamiteGoesBoom this should be resolved in v1.5.6
