### ISSUE TITLE
Not installable with composer on PHP 8

### ISSUE THREAD

**Issue by WHITE-developer** [FosterCommerce/snipcart-craft-plugin#42]
We would like to try out the plugin, but it isn't installing on PHP 8 with composer due to the ` "php": "^7.0.0",` requirement. 
Is this on purpose?

**Comment by sjcallender** [comment]
It is at this point. We haven't made it PHP 8 compatible yet. We can look into it. Unfortunately, it might be a month before we can get to it though.

**Comment by giorgiopogliani** [comment]
@sjcallender with PHP 7.4 in EOL, might be good if you could make this plugin compatible with at least 8.0, if not php 8.1

**Comment by cholawo** [comment]
@sjcallender can you provide me with a date when this will be complete?   I cannot leave sites on php 7.4 anymore given that it no longer gets security fixes.

**Comment by sjcallender** [comment]
@cholawo - Unfortunately, I can't. But I can say that we are putting eyes on it again in May and June. We'd like to get this finalized for everyone. It's been too long, we know.

**Comment by sjcallender** [comment]
This has been fixed with the release of [version 1.6.0](https://github.com/FosterCommerce/snipcart-craft-plugin/releases/tag/1.6.0).
