### ISSUE TITLE
Compatibility Issue with Snipcart 1.6.0 and PHP 7.x

### ISSUE THREAD

**Issue by handplant** [FosterCommerce/snipcart-craft-plugin#52]
I am currently working on a Craft CMS 3 project running on PHP 7.4. Unfortunately, it seems that Snipcart version 1.6.0 is no longer compatible with PHP 7.x. Due to other plugins, upgrading to PHP 8 is currently not feasible for me. I wanted to inquire if there is any possibility of making Snipcart 1.6.0 work with PHP 7.x? Your assistance or any workaround suggestions would be greatly appreciated.

Thank you!

**Comment by wbdzynr** [comment]
Grab version 1.5.7.  I'm actually running that on a Craft 3.8 site and PHP 7.4.

**Comment by handplant** [comment]
> Grab version 1.5.7. I'm actually running that on a Craft 3.8 site and PHP 7.4.

That works for me as well, but I want to be up-to-date in the future!

**Comment by sjcallender** [comment]
@handplant What other plugins are you waiting on to be compatible with Craft 4?

**Comment by handplant** [comment]
@sjcallender Hello, I'm using Imager, which is not available for Craft 4. ImagerX is not an option for now. Additionally, the client doesn't have a budget for upgrading to Craft CMS 4 and prefers to stick with version 3.

**Comment by johnnynotsolucky** [comment]
@handplant I've added back php 7.4 compat in [v1.6.1](https://github.com/FosterCommerce/snipcart-craft-plugin/releases/tag/1.6.1)
